[profile.default]
src = "contracts/src"
test = "contracts/test"
out = "contracts/out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "./contracts/out" }]

